space        cycle pause
right        seek  3
left         seek -3
shift+right  seek  30
shift+left   seek -30
m            cycle mute
up           add volume  5
down         add volume -5
/            set volume 100
[            add speed -0.25
]            add speed  0.25
\            set speed 1
t            cycle ontop
