#ytdl-format=bv[height<=1080][vcodec!=?vp9]+ba/b[height<=1080]
ytdl-format=bv[height<=1080][vcodec!~='^(vp0?9)']+ba/b[height<=1080]
#ytdl-format=bestvideo[height<=1080][fps<=?30][vcodec!=?vp9]+bestaudio/best
#ytdl-format="bestvideo[height<=?720][fps<=?30][vcodec!=?vp9]+bestaudio/best"
#ytdl-raw-options='sub-lang="en,eng,enUS,en-US",write-sub=,write-auto-sub=,format=""bv*+ba/b"",no-cookies,rm-cache-dir,no-cookies-from-browser'
ytdl-raw-options='sub-lang="en,eng,enUS,en-US",write-sub=,write-auto-sub=,no-cookies,rm-cache-dir,no-cookies-from-browser'
fs=yes
#seems its 50% volume of 80 so 40% of max for PC
volume=50
#log-file=C:\Users\User\Documents\Geoff\Apps\AV\mpv\logs.txt
save-position-on-quit=yes


#OSD =======
#Disable the whole OSD (if you use an external one like uosc)
osc=yes

#Level of OSD, some GUIs might surpress mpv OSD, so you can add it back
# osd-level=1

#Don't show a huge volume box on screen when turning the volume up/down
osd-bar=no

#OSD font size
#osd-font-size=15

#Disable the Windows border of mpv
border=no

# Don't allow new windows to be larger than the screen.
autofit-larger=100%x100%

# Enable hardware decoding if available, =yes is implied.
hwdec=yes

#https://github.com/Samillion/mpv-ytdlautoformat/blob/master/ytdlautoformat.conf
#https://github.com/Samillion/mpv-conf?tab=readme-ov-file#user-content-fnref-6-64c952a535b75ca575541b64524186f6
